# Generated by Django 2.1.4 on 2019-01-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次更新日期'),
        ),
    ]
