# Generated by Django 2.1.4 on 2019-01-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_author_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='有效', max_length=10, verbose_name='状态'),
        ),
    ]
