# Generated by Django 2.1.4 on 2019-01-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
