# Generated by Django 2.1.4 on 2019-01-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
