# Generated by Django 2.1.4 on 2018-12-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('operate', models.CharField(max_length=200)),
            ],
        ),
    ]
